import matplotlib
from matplotlib import interactive
from matplotlib import pyplot as plt
import pandas as pd

df = pd.read_csv(r"\\wsl.localhost\Ubuntu-22.04\home\ralph\workspace\adda\cylsph\run000_cylinder_g128_m1.5\ampl_scatgrid", sep=" ")
df1=pd.DataFrame(df["theta"].values, columns=["theta"])
df1.insert(1,"s1",(df["s1.r"].pow(2).add(df["s1.i"].pow(2))).mul(1))
df1.insert(2,"s2",(df["s2.r"].pow(2).add(df["s2.i"].pow(2))).mul(1))
df1.insert(3,"s3",df["s3.r"].pow(2).add(df["s3.i"].pow(2)))
df1.insert(4,"s4",df["s4.r"].pow(2).add(df["s4.i"].pow(2)))
df1.plot(x="theta",y=["s1","s2"])
plt.yscale("log")
plt.savefig('figure0.pdf')

df = pd.read_csv(r"\\wsl.localhost\Ubuntu-22.04\home\ralph\workspace\adda\cylsph\run001_cylinder_g64_m1.5\ampl_scatgrid", sep=" ")
df1=pd.DataFrame(df["theta"].values, columns=["theta"])
df1.insert(1,"s1",(df["s1.r"].pow(2).add(df["s1.i"].pow(2))).mul(1))
df1.insert(2,"s2",(df["s2.r"].pow(2).add(df["s2.i"].pow(2))).mul(1))
df1.insert(3,"s3",df["s3.r"].pow(2).add(df["s3.i"].pow(2)))
df1.insert(4,"s4",df["s4.r"].pow(2).add(df["s4.i"].pow(2)))
df1.plot(x="theta",y=["s1","s2"])
plt.yscale("log")
plt.savefig('figure1.pdf')

df = pd.read_csv(r"\\wsl.localhost\Ubuntu-22.04\home\ralph\workspace\adda\cylsph\run002_cylinder_g32_m1.5\ampl_scatgrid", sep=" ")
df1=pd.DataFrame(df["theta"].values, columns=["theta"])
df1.insert(1,"s1",(df["s1.r"].pow(2).add(df["s1.i"].pow(2))).mul(1))
df1.insert(2,"s2",(df["s2.r"].pow(2).add(df["s2.i"].pow(2))).mul(1))
df1.insert(3,"s3",df["s3.r"].pow(2).add(df["s3.i"].pow(2)))
df1.insert(4,"s4",df["s4.r"].pow(2).add(df["s4.i"].pow(2)))
df1.plot(x="theta",y=["s1","s2"])
plt.yscale("log")
plt.savefig('figure2.pdf')

df = pd.read_csv(r"\\wsl.localhost\Ubuntu-22.04\home\ralph\workspace\adda\cylsph\run003_cylinder_g32_m1.5\ampl_scatgrid", sep=" ")
df1=pd.DataFrame(df["theta"].values, columns=["theta"])
df1.insert(1,"s1",(df["s1.r"].pow(2).add(df["s1.i"].pow(2))).mul(1))
df1.insert(2,"s2",(df["s2.r"].pow(2).add(df["s2.i"].pow(2))).mul(1))
df1.insert(3,"s3",df["s3.r"].pow(2).add(df["s3.i"].pow(2)))
df1.insert(4,"s4",df["s4.r"].pow(2).add(df["s4.i"].pow(2)))
df1.plot(x="theta",y=["s1","s2"])
plt.yscale("log")
plt.savefig('figure3.pdf')

df = pd.read_csv(r"\\wsl.localhost\Ubuntu-22.04\home\ralph\workspace\adda\cylsph\run004_cylinder_g32_m1.5\ampl_scatgrid", sep=" ")
df1=pd.DataFrame(df["theta"].values, columns=["theta"])
df1.insert(1,"s1",(df["s1.r"].pow(2).add(df["s1.i"].pow(2))).mul(1))
df1.insert(2,"s2",(df["s2.r"].pow(2).add(df["s2.i"].pow(2))).mul(1))
df1.insert(3,"s3",df["s3.r"].pow(2).add(df["s3.i"].pow(2)))
df1.insert(4,"s4",df["s4.r"].pow(2).add(df["s4.i"].pow(2)))
df1.plot(x="theta",y=["s1","s2"])
plt.yscale("log")
plt.savefig('figure4.pdf')

df = pd.read_csv(r"\\wsl.localhost\Ubuntu-22.04\home\ralph\workspace\adda\cylsph\run005_cylinder_g16_m1.5\ampl_scatgrid", sep=" ")
df1=pd.DataFrame(df["theta"].values, columns=["theta"])
df1.insert(1,"s1",(df["s1.r"].pow(2).add(df["s1.i"].pow(2))).mul(1))
df1.insert(2,"s2",(df["s2.r"].pow(2).add(df["s2.i"].pow(2))).mul(1))
df1.insert(3,"s3",df["s3.r"].pow(2).add(df["s3.i"].pow(2)))
df1.insert(4,"s4",df["s4.r"].pow(2).add(df["s4.i"].pow(2)))
df1.plot(x="theta",y=["s1","s2"])
plt.yscale("log")
plt.savefig('figure5.pdf')

df = pd.read_csv(r"\\wsl.localhost\Ubuntu-22.04\home\ralph\workspace\adda\cylsph\run006_cylinder_g40_m1.5\ampl_scatgrid", sep=" ")
df1=pd.DataFrame(df["theta"].values, columns=["theta"])
df1.insert(1,"s1",df["s1.r"].pow(2).add(df["s1.i"].pow(2)))
df1.insert(2,"s2",df["s2.r"].pow(2).add(df["s2.i"].pow(2)))
df1.insert(3,"s3",df["s3.r"].pow(2).add(df["s3.i"].pow(2)))
df1.insert(4,"s4",df["s4.r"].pow(2).add(df["s4.i"].pow(2)))
df1.plot(x="theta",y=["s1","s2"])
plt.yscale("log")
plt.savefig('figure6.pdf')

df = pd.read_csv(r"\\wsl.localhost\Ubuntu-22.04\home\ralph\workspace\adda\cylsph\run007_cylinder_g50_m1.5\ampl_scatgrid", sep=" ")
df1=pd.DataFrame(df["theta"].values, columns=["theta"])
df1.insert(1,"s1",df["s1.r"].pow(2).add(df["s1.i"].pow(2)))
df1.insert(2,"s2",df["s2.r"].pow(2).add(df["s2.i"].pow(2)))
df1.insert(3,"s3",df["s3.r"].pow(2).add(df["s3.i"].pow(2)))
df1.insert(4,"s4",df["s4.r"].pow(2).add(df["s4.i"].pow(2)))
df1.plot(x="theta",y=["s1","s2"])
plt.yscale("log")
plt.savefig('figure7.pdf')

df = pd.read_csv(r"\\wsl.localhost\Ubuntu-22.04\home\ralph\workspace\adda\cylsph\run008_cylinder_g50_m1.5\ampl_scatgrid", sep=" ")
df1=pd.DataFrame(df["theta"].values, columns=["theta"])
df1.insert(1,"s1",df["s1.r"].pow(2).add(df["s1.i"].pow(2)))
df1.insert(2,"s2",df["s2.r"].pow(2).add(df["s2.i"].pow(2)))
df1.insert(3,"s3",df["s3.r"].pow(2).add(df["s3.i"].pow(2)))
df1.insert(4,"s4",df["s4.r"].pow(2).add(df["s4.i"].pow(2)))
df1.plot(x="theta",y=["s1","s2"])
plt.yscale("log")
plt.savefig('figure8.pdf')

df = pd.read_csv(r"\\wsl.localhost\Ubuntu-22.04\home\ralph\workspace\adda\cylsph\run009_cylinder_g55_m1.5\ampl_scatgrid", sep=" ")
df1=pd.DataFrame(df["theta"].values, columns=["theta"])
df1.insert(1,"s1",df["s1.r"].pow(2).add(df["s1.i"].pow(2)))
df1.insert(2,"s2",df["s2.r"].pow(2).add(df["s2.i"].pow(2)))
df1.insert(3,"s3",df["s3.r"].pow(2).add(df["s3.i"].pow(2)))
df1.insert(4,"s4",df["s4.r"].pow(2).add(df["s4.i"].pow(2)))
df1.plot(x="theta",y=["s1","s2"])
plt.yscale("log")
plt.savefig('figure9.pdf')